In [299]:
import pandas as pd
import numpy as np

In [300]:
train = pd.read_csv("data/train.csv", header = 0)

In [301]:
train.describe()

Id   MSSubClass  LotFrontage        LotArea  OverallQual  \
count  1460.000000  1460.000000  1201.000000    1460.000000  1460.000000   
mean    730.500000    56.897260    70.049958   10516.828082     6.099315   
std     421.610009    42.300571    24.284752    9981.264932     1.382997   
min       1.000000    20.000000    21.000000    1300.000000     1.000000   
25%     365.750000    20.000000    59.000000    7553.500000     5.000000   
50%     730.500000    50.000000    69.000000    9478.500000     6.000000   
75%    1095.250000    70.000000    80.000000   11601.500000     7.000000   
max    1460.000000   190.000000   313.000000  215245.000000    10.000000   

       OverallCond    YearBuilt  YearRemodAdd   MasVnrArea   BsmtFinSF1  \
count  1460.000000  1460.000000   1460.000000  1452.000000  1460.000000   
mean      5.575342  1971.267808   1984.865753   103.685262   443.639726   
std       1.112799    30.202904     20.645407   181.066207   456.098091   
min       1.000000  1872.000000   1950.000000     0.000000     0.000000   
25%       5.000000  1954.000000   1967.000000     0.000000     0.000000   
50%       5.000000  1973.000000   1994.000000     0.000000   383.500000   
75%       6.000000  2000.000000   2004.000000   166.000000   712.250000   
max       9.000000  2010.000000   2010.000000  1600.000000  5644.000000   

           ...         WoodDeckSF  OpenPorchSF  EnclosedPorch    3SsnPorch  \
count      ...        1460.000000  1460.000000    1460.000000  1460.000000   
mean       ...          94.244521    46.660274      21.954110     3.409589   
std        ...         125.338794    66.256028      61.119149    29.317331   
min        ...           0.000000     0.000000       0.000000     0.000000   
25%        ...           0.000000     0.000000       0.000000     0.000000   
50%        ...           0.000000    25.000000       0.000000     0.000000   
75%        ...         168.000000    68.000000       0.000000     0.000000   
max        ...         857.000000   547.000000     552.000000   508.000000   

       ScreenPorch     PoolArea       MiscVal       MoSold       YrSold  \
count  1460.000000  1460.000000   1460.000000  1460.000000  1460.000000   
mean     15.060959     2.758904     43.489041     6.321918  2007.815753   
std      55.757415    40.177307    496.123024     2.703626     1.328095   
min       0.000000     0.000000      0.000000     1.000000  2006.000000   
25%       0.000000     0.000000      0.000000     5.000000  2007.000000   
50%       0.000000     0.000000      0.000000     6.000000  2008.000000   
75%       0.000000     0.000000      0.000000     8.000000  2009.000000   
max     480.000000   738.000000  15500.000000    12.000000  2010.000000   

           SalePrice  
count    1460.000000  
mean   180921.195890  
std     79442.502883  
min     34900.000000  
25%    129975.000000  
50%    163000.000000  
75%    214000.000000  
max    755000.000000  

[8 rows x 38 columns]

In [302]:
train.shape

(1460, 81)

 Below is information on the missing values of each feature in descending order. We removed every feature whose missing values were above 50%.

In [303]:
train.columns.values

array(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt',
       'YearRemodAdd', 'RoofStyle', 'RoofMatl', 'Exterior1st',
       'Exterior2nd', 'MasVnrType', 'MasVnrArea', 'ExterQual', 'ExterCond',
       'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure',
       'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2', 'BsmtFinSF2',
       'BsmtUnfSF', 'TotalBsmtSF', 'Heating', 'HeatingQC', 'CentralAir',
       'Electrical', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF', 'GrLivArea',
       'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath',
       'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual', 'TotRmsAbvGrd',
       'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea',
       'GarageQual', 'GarageCond', 'Pav

In [304]:
missing_perc=train.apply(lambda x: 100*(1-x.count().sum()/(1.0*len(x))))
sorted_missing = missing_perc.sort_values(ascending = False)
sorted_missing.nlargest(15)

PoolQC          99.520548
MiscFeature     96.301370
Alley           93.767123
Fence           80.753425
FireplaceQu     47.260274
LotFrontage     17.739726
GarageCond       5.547945
GarageType       5.547945
GarageYrBlt      5.547945
GarageFinish     5.547945
GarageQual       5.547945
BsmtExposure     2.602740
BsmtFinType2     2.602740
BsmtFinType1     2.534247
BsmtCond         2.534247
dtype: float64

In [305]:
del train['MiscFeature']
del train['Alley']
del train['Fence']
del train['PoolQC']

In [306]:
train.shape

(1460, 77)

In [307]:
test = pd.read_csv("test.csv", header = 0)

In [308]:
test.shape

(1459, 80)

In [309]:
del test['MiscFeature']
del test['Alley']
del test['Fence']
del test['PoolQC']

In [310]:
test.shape

(1459, 76)

We then go ahead an impute missing values of the remaining features. For continous features, we impute missing values 
with mean. For categorical features, we impute missing values with mode.

In [311]:
from sklearn import preprocessing 

In [312]:
"""
The function below imputes missing values. If the feature is categorical, mode is used, else, mean is used
"""
import pandas as pd
import numpy as np

from sklearn.base import TransformerMixin

class DataFrameImputer(TransformerMixin):

    def __init__(self):
        """Impute missing values.

        Columns of dtype object are imputed with the most frequent value 
        in column.

        Columns of other types are imputed with mean of column.

        """
    def fit(self, X, y=None):

        self.fill = pd.Series([X[c].value_counts().index[0]
            if X[c].dtype == np.dtype('O') else X[c].mean() for c in X],
            index=X.columns)

        return self

    def transform(self, X, y=None):
        return X.fillna(self.fill)

In [313]:
imputed_train = DataFrameImputer().fit_transform(train)
imputed_train.to_csv('data/imputed_train.csv', index = False)

In [314]:
imputed_train.shape

(1460, 77)

In [315]:
imputed_test = DataFrameImputer().fit_transform(test)
imputed_test.to_csv('imputed_test.csv', index = False)

In [316]:
imputed_test.shape

(1459, 76)

In [317]:
dummy_target = imputed_train['SalePrice']

We then set the SalePrice as the target and remove it from the training dataset

In [318]:
del imputed_train['SalePrice']

# One Hot Encoding

After imputing mising values we join both test and train before creating dummy variables to ensures the final number of columns are the same.

In [319]:
full_table = [imputed_train, imputed_test]

In [320]:
full_table = pd.concat(full_table)

In [321]:
full_table.shape

(2919, 76)

In [322]:
full_table = pd.get_dummies(full_table)

In [323]:
full_table.shape

(2919, 276)

In [324]:
dummy_train = full_table[:1460]

In [325]:
dummy_test = full_table[1460:]

When we check for missing values, we see none of the columns have missing values.

In [326]:
missing_perc=imputed_train.apply(lambda x: 100*(1-x.count().sum()/(1.0*len(x))))
sorted_missing = missing_perc.sort_values(ascending = False)
sorted_missing.nlargest(10)

SaleCondition    0.0
ExterCond        0.0
RoofStyle        0.0
RoofMatl         0.0
Exterior1st      0.0
Exterior2nd      0.0
MasVnrType       0.0
MasVnrArea       0.0
ExterQual        0.0
Foundation       0.0
dtype: float64

# Evaluation

## Baseline Model  (Linear Regression)

In [327]:
from sklearn.linear_model import LinearRegression

In [328]:
lm = LinearRegression()
scores = cross_val_score(lm, dummy_train, dummy_target, cv=5, scoring = 'r2')
print(scores)
print ("The r2 score of the Linear regression model is :%0.3f"%np.mean((scores)))

[ 0.84880353  0.81778274  0.80946675  0.88757933  0.66944689]
The r2 score of the Linear regression model is :0.807


## RandomForestregressor

In [329]:
from sklearn.model_selection import cross_val_score
from sklearn import metrics
from sklearn.ensemble import RandomForestRegressor

In [330]:
forest = RandomForestRegressor()
scores = cross_val_score(forest, dummy_train, dummy_target, cv=5, scoring = 'r2')
print(scores)
print ("The r2 score of the RandomForest model is : %0.3f"%np.mean((scores)))

[ 0.85038379  0.82832106  0.88050796  0.84828993  0.84405914]
The r2 score of the RandomForest model is : 0.850


## AdaBoostRegressor

In [331]:
from sklearn.ensemble import AdaBoostRegressor
from sklearn.tree import DecisionTreeRegressor

In [332]:
regr = AdaBoostRegressor()
scores = cross_val_score(regr, dummy_train, dummy_target, cv=5, scoring = 'r2')
print(scores)
print ("The r2 score of AdaBoost regression model is : %0.3f"%np.mean((scores)))

[ 0.81444754  0.78336607  0.81599211  0.80191888  0.74755715]
The r2 score of AdaBoost regression model is : 0.793


### LinearRegression Scores 

In [333]:
lm = LinearRegression()
lm.fit(dummy_train,dummy_target)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [334]:
lm.score(dummy_train,dummy_target)

0.93061237134940678